import Link from "next/link";
import { desc, ilike, or } from "drizzle-orm";
import { db } from "@/lib/db";
import { profiles } from "@/lib/db/schema";

export default async function AdminCustomersPage({ searchParams }: { searchParams: Promise<{ q?: string }> }) {
  const q = (await searchParams).q?.trim() ?? "";
  const customers = await db.select().from(profiles).where(q ? or(ilike(profiles.fullName, `%${q}%`), ilike(profiles.phone, `%${q}%`)) : undefined).orderBy(desc(profiles.createdAt));
  return <section className="flex flex-col gap-6"><div><p className="font-mono text-xs uppercase tracking-[0.2em] text-[#8a1018]">Relationships</p><h1 className="mt-2 font-serif text-4xl font-bold">Customers</h1><p className="mt-2 text-[#6d5e5a]">Customer accounts and delivery relationships.</p></div><form method="get" className="flex gap-3"><input name="q" defaultValue={q} placeholder="Search name or phone" className="w-full rounded-xl border border-[#d9c9a2] bg-[#fffdf7] px-4 py-3 text-sm outline-none focus:ring-2 focus:ring-[#67040b]" /><button className="rounded-xl bg-[#67040b] px-5 py-3 text-sm font-semibold text-white">Search</button></form><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{(customers ?? []).map((customer) => <article key={customer.id} className="rounded-2xl border border-[#d9c9a2] bg-[#fffdf7] p-5"><div className="flex items-center gap-3"><div className="flex size-11 items-center justify-center rounded-full bg-[#67040b] font-serif text-lg font-bold text-[#dcb45a]">{(customer.fullName ?? customer.phone ?? "C").charAt(0).toUpperCase()}</div><div><h2 className="font-semibold">{customer.fullName ?? "Unnamed customer"}</h2><p className="text-sm text-[#6d5e5a]">{customer.phone ?? "No email listed"}</p></div></div><div className="mt-5 flex justify-between border-t border-[#eadfc5] pt-4 text-xs text-[#6d5e5a]"><span className="capitalize">{customer.role ?? "customer"}</span><span>{new Date(customer.createdAt).toLocaleDateString()}</span></div></article>)}{!customers?.length ? <p className="rounded-2xl border border-dashed border-[#d9c9a2] p-10 text-center text-sm text-[#6d5e5a] md:col-span-2 xl:col-span-3">No customer profiles found.</p> : null}</div></section>;
}
