import { pgTable, text, timestamp, uuid, integer, boolean, doublePrecision, jsonb } from "drizzle-orm/pg-core"

export const user = pgTable("user", { id: text("id").primaryKey(), name: text("name").notNull(), email: text("email").notNull().unique(), emailVerified: boolean("emailVerified").notNull().default(false), image: text("image"), createdAt: timestamp("createdAt").notNull().defaultNow(), updatedAt: timestamp("updatedAt").notNull().defaultNow() })
export const session = pgTable("session", { id: text("id").primaryKey(), expiresAt: timestamp("expiresAt").notNull(), token: text("token").notNull().unique(), createdAt: timestamp("createdAt").notNull().defaultNow(), updatedAt: timestamp("updatedAt").notNull().defaultNow(), ipAddress: text("ipAddress"), userAgent: text("userAgent"), userId: text("userId").notNull() })
export const account = pgTable("account", { id: text("id").primaryKey(), accountId: text("accountId").notNull(), providerId: text("providerId").notNull(), userId: text("userId").notNull(), accessToken: text("accessToken"), refreshToken: text("refreshToken"), idToken: text("idToken"), accessTokenExpiresAt: timestamp("accessTokenExpiresAt"), refreshTokenExpiresAt: timestamp("refreshTokenExpiresAt"), scope: text("scope"), password: text("password"), createdAt: timestamp("createdAt").notNull().defaultNow(), updatedAt: timestamp("updatedAt").notNull().defaultNow() })
export const verification = pgTable("verification", { id: text("id").primaryKey(), identifier: text("identifier").notNull(), value: text("value").notNull(), expiresAt: timestamp("expiresAt").notNull(), createdAt: timestamp("createdAt").defaultNow(), updatedAt: timestamp("updatedAt").defaultNow() })

export const profiles = pgTable("profiles", { id: uuid("id").primaryKey(), fullName: text("full_name"), role: text("role").notNull().default("customer"), phone: text("phone"), createdAt: timestamp("created_at").notNull().defaultNow(), updatedAt: timestamp("updated_at").notNull().defaultNow() })
export const customers = pgTable("customers", { id: uuid("id").defaultRandom().primaryKey(), profileId: uuid("profile_id"), name: text("name").notNull(), email: text("email").notNull(), phone: text("phone"), company: text("company"), createdAt: timestamp("created_at").notNull().defaultNow() })
export const addresses = pgTable("addresses", { id: uuid("id").defaultRandom().primaryKey(), customerId: uuid("customer_id"), label: text("label").notNull(), line1: text("line1").notNull(), line2: text("line2"), city: text("city").notNull(), state: text("state"), postalCode: text("postal_code"), country: text("country").notNull(), latitude: doublePrecision("latitude"), longitude: doublePrecision("longitude"), createdAt: timestamp("created_at").notNull().defaultNow() })
export const shipments = pgTable("shipments", { id: uuid("id").defaultRandom().primaryKey(), trackingNumber: text("tracking_number").notNull().unique(), customerId: uuid("customer_id"), origin: text("origin").notNull(), destination: text("destination").notNull(), originLat: doublePrecision("origin_lat"), originLng: doublePrecision("origin_lng"), destinationLat: doublePrecision("destination_lat"), destinationLng: doublePrecision("destination_lng"), status: text("status").notNull().default("pending"), eta: timestamp("eta"), driverName: text("driver_name"), vehicle: text("vehicle"), lastUpdate: text("last_update"), createdByUserId: text("created_by_user_id"), createdByRole: text("created_by_role").notNull().default("customer"), packageDetails: jsonb("package_details").notNull().default({}), carrier: text("carrier"), shippingCost: integer("shipping_cost"), paymentStatus: text("payment_status").notNull().default("unpaid"), createdAt: timestamp("created_at").notNull().defaultNow(), updatedAt: timestamp("updated_at").notNull().defaultNow() })
export const trackingEvents = pgTable("tracking_events", { id: uuid("id").defaultRandom().primaryKey(), shipmentId: uuid("shipment_id").notNull(), status: text("status").notNull(), location: text("location"), latitude: doublePrecision("latitude"), longitude: doublePrecision("longitude"), message: text("message").notNull(), createdAt: timestamp("created_at").notNull().defaultNow() })
export const shipmentDocuments = pgTable("shipment_documents", { id: uuid("id").defaultRandom().primaryKey(), shipmentId: uuid("shipment_id").notNull(), storageKey: text("storage_key").notNull(), fileName: text("file_name").notNull(), mimeType: text("mime_type"), createdAt: timestamp("created_at").notNull().defaultNow() })
export const invoices = pgTable("invoices", { id: uuid("id").defaultRandom().primaryKey(), shipmentId: uuid("shipment_id"), customerId: uuid("customer_id"), invoiceNumber: text("invoice_number").notNull().unique(), amountCents: integer("amount_cents").notNull(), status: text("status").notNull().default("draft"), dueAt: timestamp("due_at"), createdAt: timestamp("created_at").notNull().defaultNow() })
export const notifications = pgTable("notifications", { id: uuid("id").defaultRandom().primaryKey(), userId: text("user_id"), shipmentId: uuid("shipment_id"), title: text("title").notNull(), message: text("message").notNull(), read: boolean("read").notNull().default(false), metadata: jsonb("metadata"), createdAt: timestamp("created_at").notNull().defaultNow() })
export const shippoRates = pgTable("shippo_rates", { id: uuid("id").defaultRandom().primaryKey(), shipmentId: uuid("shipment_id"), provider: text("provider").notNull(), serviceLevel: text("service_level").notNull(), amountCents: integer("amount_cents").notNull(), currency: text("currency").notNull().default("USD"), estimatedDays: integer("estimated_days"), raw: jsonb("raw"), createdAt: timestamp("created_at").notNull().defaultNow() })
export const shippoLabels = pgTable("shippo_labels", { id: uuid("id").defaultRandom().primaryKey(), shipmentId: uuid("shipment_id"), transactionId: text("transaction_id"), carrier: text("carrier").notNull(), labelFormat: text("label_format").notNull(), labelDownload: jsonb("label_download"), customsFormUrl: text("customs_form_url"), raw: jsonb("raw"), createdAt: timestamp("created_at").notNull().defaultNow() })
export const shippoWebhookEvents = pgTable("shippo_webhook_events", { id: uuid("id").defaultRandom().primaryKey(), eventId: text("event_id").notNull().unique(), eventType: text("event_type").notNull(), trackingNumber: text("tracking_number"), payload: jsonb("payload").notNull(), receivedAt: timestamp("received_at").notNull().defaultNow() })
export const auditLogs = pgTable("audit_logs", { id: uuid("id").defaultRandom().primaryKey(), userId: text("user_id"), action: text("action").notNull(), resource: text("resource").notNull(), resourceId: text("resource_id"), description: text("description").notNull(), createdAt: timestamp("created_at").notNull().defaultNow() })
export const facilities = pgTable("facilities", { id: uuid("id").defaultRandom().primaryKey(), name: text("name").notNull(), address: text("address"), country: text("country"), contactInformation: text("contact_information"), operatingStatus: text("operating_status").notNull().default("active"), createdAt: timestamp("created_at").notNull().defaultNow(), updatedAt: timestamp("updated_at").notNull().defaultNow() })
export const drivers = pgTable("drivers", { id: uuid("id").defaultRandom().primaryKey(), name: text("name").notNull(), email: text("email"), phone: text("phone"), status: text("status").notNull().default("available"), createdAt: timestamp("created_at").notNull().defaultNow() })

export const shippingCarriers = pgTable("shipping_carriers", { id: uuid("id").defaultRandom().primaryKey(), code: text("code").notNull().unique(), name: text("name").notNull(), provider: text("provider").notNull(), active: boolean("active").notNull().default(true), createdAt: timestamp("created_at").notNull().defaultNow() })
export const shippingShipments = pgTable("shipping_shipments", { id: uuid("id").defaultRandom().primaryKey(), userId: text("user_id").notNull(), publicId: text("public_id").notNull().unique(), status: text("status").notNull().default("draft"), origin: jsonb("origin").notNull(), destination: jsonb("destination").notNull(), currency: text("currency").notNull().default("USD"), carrierCode: text("carrier_code"), serviceCode: text("service_code"), shippingCostCents: integer("shipping_cost_cents"), insuranceCents: integer("insurance_cents").notNull().default(0), signatureRequired: boolean("signature_required").notNull().default(false), referenceNumber: text("reference_number"), notes: text("notes"), trackingNumber: text("tracking_number").unique(), estimatedDelivery: timestamp("estimated_delivery"), createdAt: timestamp("created_at").notNull().defaultNow(), updatedAt: timestamp("updated_at").notNull().defaultNow() })
export const shippingParcels = pgTable("shipping_parcels", { id: uuid("id").defaultRandom().primaryKey(), shipmentId: uuid("shipment_id").notNull(), userId: text("user_id").notNull(), weight: doublePrecision("weight").notNull(), weightUnit: text("weight_unit").notNull().default("kg"), length: doublePrecision("length"), width: doublePrecision("width"), height: doublePrecision("height"), dimensionUnit: text("dimension_unit").notNull().default("cm"), packageType: text("package_type").notNull().default("parcel"), description: text("description"), quantity: integer("quantity").notNull().default(1), declaredValueCents: integer("declared_value_cents").notNull().default(0), createdAt: timestamp("created_at").notNull().defaultNow() })
export const shippingRates = pgTable("shipping_rates", { id: uuid("id").defaultRandom().primaryKey(), shipmentId: uuid("shipment_id").notNull(), userId: text("user_id").notNull(), carrierCode: text("carrier_code").notNull(), carrierName: text("carrier_name").notNull(), serviceName: text("service_name").notNull(), serviceCode: text("service_code").notNull(), amountCents: integer("amount_cents").notNull(), currency: text("currency").notNull(), estimatedDelivery: timestamp("estimated_delivery"), estimatedDays: integer("estimated_days"), taxesCents: integer("taxes_cents").notNull().default(0), feesCents: integer("fees_cents").notNull().default(0), totalCents: integer("total_cents").notNull(), raw: jsonb("raw"), createdAt: timestamp("created_at").notNull().defaultNow() })
export const shippingLabels = pgTable("shipping_labels", { id: uuid("id").defaultRandom().primaryKey(), shipmentId: uuid("shipment_id").notNull(), userId: text("user_id").notNull(), labelId: text("label_id").notNull(), trackingNumber: text("tracking_number"), carrierCode: text("carrier_code").notNull(), serviceCode: text("service_code"), labelFormat: text("label_format").notNull(), labelUrl: text("label_url"), fileReference: text("file_reference"), createdAt: timestamp("created_at").notNull().defaultNow() })
export const shippingTrackingEvents = pgTable("shipping_tracking_events", { id: uuid("id").defaultRandom().primaryKey(), shipmentId: uuid("shipment_id").notNull(), userId: text("user_id").notNull(), eventKey: text("event_key").notNull(), status: text("status").notNull(), location: text("location"), latitude: doublePrecision("latitude"), longitude: doublePrecision("longitude"), message: text("message").notNull(), occurredAt: timestamp("occurred_at").notNull().defaultNow(), createdAt: timestamp("created_at").notNull().defaultNow() })
export const shippingEvents = pgTable("shipping_events", { id: uuid("id").defaultRandom().primaryKey(), shipmentId: uuid("shipment_id").notNull(), userId: text("user_id").notNull(), eventType: text("event_type").notNull(), idempotencyKey: text("idempotency_key").notNull().unique(), payload: jsonb("payload").notNull(), createdAt: timestamp("created_at").notNull().defaultNow() })

export const schema = { user, session, account, verification, profiles, customers, addresses, shipments, trackingEvents, shipmentDocuments, invoices, notifications, shippoRates, shippoLabels, shippoWebhookEvents, auditLogs, facilities, drivers, shippingCarriers, shippingShipments, shippingParcels, shippingRates, shippingLabels, shippingTrackingEvents, shippingEvents }

export type Shipment = typeof shipments.$inferSelect
export type TrackingEvent = typeof trackingEvents.$inferSelect
export type Notification = typeof notifications.$inferSelect
