"use client"

import { useMemo, useState } from "react"
import { AlertCircle, ArrowDownToLine, CheckCircle2, CreditCard, FileText, Mail, MoreHorizontal, Printer, ReceiptText, RefreshCcw, ShieldCheck, WalletCards, XCircle } from "lucide-react"
import { DashboardLayout } from "@/components/layouts/dashboard-layout"
import { Card } from "@/components/ui/card"
import { Button } from "@/components/ui/button"

const invoices = [
  { number: "INV-2026-0048", shipment: "UNF-784923105", customer: "Maya Chen", service: "Priority", amount: 14.5, status: "Paid", date: "Aug 15, 2026", email: "maya.chen@example.com" },
  { number: "INV-2026-0047", shipment: "UNF-784923104", customer: "Northstar Studio", service: "Ground", amount: 8.95, status: "Refund pending", date: "Aug 14, 2026", email: "ops@northstar.example" },
  { number: "INV-2026-0046", shipment: "UNF-784923103", customer: "Jules Martin", service: "Express", amount: 24, status: "Paid", date: "Aug 13, 2026", email: "jules.martin@example.com" },
]

const statusStyles: Record<string, string> = { Paid: "border-success/30 bg-success/10 text-success", "Refund pending": "border-primary/30 bg-primary/10 text-primary", Failed: "border-destructive/30 bg-destructive/10 text-destructive" }
function Badge({ children, className = "" }: { children: React.ReactNode; variant?: string; className?: string }) { return <span className={`inline-flex items-center rounded-full border px-2.5 py-0.5 text-xs font-medium ${className}`}>{children}</span> }
function Tabs({ children, className = "" }: { children: React.ReactNode; defaultValue?: string; className?: string }) { return <div className={className}>{children}</div> }
function TabsList({ children, className = "" }: { children: React.ReactNode; className?: string }) { return <div className={`mb-4 grid h-auto w-full grid-cols-3 rounded-md bg-muted/60 p-1 ${className}`}>{children}</div> }
function TabsTrigger({ children, value }: { children: React.ReactNode; value: string }) { return <button type="button" className="rounded-sm px-3 py-2 text-sm font-medium text-muted-foreground">{children}</button> }
function TabsContent({ children, className = "", value }: { children: React.ReactNode; value: string; className?: string }) { return <div className={className}>{children}</div> }

export default function BillingPage() {
  const [paymentState, setPaymentState] = useState<"ready" | "success" | "failed">("ready")
  const [selectedInvoice, setSelectedInvoice] = useState(invoices[0])
  const total = useMemo(() => selectedInvoice.amount, [selectedInvoice])

  return <DashboardLayout><div className="mx-auto flex max-w-6xl flex-col gap-6">
    <div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="font-mono text-xs uppercase tracking-[0.24em] text-primary">Financial operations</p><h1 className="mt-2 text-3xl font-bold tracking-tight md:text-4xl">Billing & invoices</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">Review shipment charges, simulate payment states, and prepare customer receipts. Payments are not connected in this preview.</p></div><div className="flex items-center gap-2 rounded-full border border-primary/20 bg-primary/5 px-3 py-2 text-xs text-primary"><ShieldCheck className="size-4" /> UI preview · no charge</div></div>
    <div className="grid gap-4 sm:grid-cols-3"><Metric icon={WalletCards} label="This month" value="$47.45" detail="3 shipment charges" /><Metric icon={ReceiptText} label="Paid invoices" value="2" detail="100% reconciled" /><Metric icon={RefreshCcw} label="Refunds" value="$8.95" detail="1 pending review" /></div>
    <Tabs defaultValue="checkout" className="w-full"><TabsList className="grid h-auto w-full grid-cols-3 bg-muted/60 p-1"><TabsTrigger value="checkout">Checkout</TabsTrigger><TabsTrigger value="invoices">Invoices</TabsTrigger><TabsTrigger value="history">Payment history</TabsTrigger></TabsList>
      <TabsContent value="checkout" className="mt-5"><div className="grid gap-5 lg:grid-cols-[1.15fr_.85fr]">
        <Card className="p-5 md:p-7"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-wider text-primary">Step 04 / Checkout</p><h2 className="mt-2 text-2xl font-semibold">Confirm payment</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">This is a display-only payment screen. Connect Stripe later to enable secure payment collection and webhooks.</p></div><CreditCard className="size-6 text-primary" /></div><div className="mt-6 flex flex-col gap-3 rounded-lg border bg-background/60 p-4"><Row label="Shipment" value="UNF-784923105" mono /><Row label="Service" value="Priority · 2–3 days" /><Row label="Route" value="New York, NY → Boston, MA" /><Row label="Customer" value="Maya Chen" /><div className="my-1 border-t border-border" /><Row label="Shipping total" value={`$${total.toFixed(2)} USD`} strong /></div><div className="mt-5 flex flex-wrap gap-3"><Button onClick={() => setPaymentState("success")}><CheckCircle2 /> Simulate successful payment</Button><Button variant="outline" onClick={() => setPaymentState("failed")}><XCircle /> Simulate failure</Button></div></Card>
        <PaymentState state={paymentState} invoice={selectedInvoice} />
      </div></TabsContent>
      <TabsContent value="invoices" className="mt-5"><InvoicePanel invoice={selectedInvoice} onPrint={() => window.print()} onDownload={() => window.print()} /></TabsContent>
      <TabsContent value="history" className="mt-5"><Card className="overflow-hidden"><div className="flex items-center justify-between border-b p-5"><div><h2 className="font-semibold">Payment history</h2><p className="text-sm text-muted-foreground">Shipment-linked payment and refund status.</p></div><Button variant="outline" size="sm"><ArrowDownToLine /> Export</Button></div><div className="divide-y divide-border">{invoices.map((invoice) => <button key={invoice.number} onClick={() => setSelectedInvoice(invoice)} className="flex w-full flex-col gap-3 p-5 text-left transition-colors hover:bg-muted/30 md:flex-row md:items-center md:justify-between"><div className="flex items-start gap-3"><div className="rounded-md border bg-muted/40 p-2"><ReceiptText className="size-4 text-primary" /></div><div><p className="font-medium">{invoice.number}</p><p className="mt-1 text-sm text-muted-foreground">{invoice.shipment} · {invoice.customer}</p></div></div><div className="flex items-center gap-5 pl-11 md:pl-0"><div><p className="font-mono text-sm">${invoice.amount.toFixed(2)}</p><p className="text-xs text-muted-foreground">{invoice.date}</p></div><Badge variant="outline" className={statusStyles[invoice.status]}>{invoice.status}</Badge><MoreHorizontal className="hidden size-4 text-muted-foreground sm:block" /></div></button>)}</div></Card></TabsContent>
    </Tabs>
  </div></DashboardLayout>
}

function Metric({ icon: Icon, label, value, detail }: { icon: typeof WalletCards; label: string; value: string; detail: string }) { return <Card className="flex items-center gap-4 p-4"><div className="rounded-md bg-primary/10 p-2.5 text-primary"><Icon className="size-5" /></div><div><p className="text-xs uppercase tracking-wider text-muted-foreground">{label}</p><p className="mt-1 text-xl font-semibold">{value}</p><p className="text-xs text-muted-foreground">{detail}</p></div></Card> }
function Row({ label, value, mono, strong }: { label: string; value: string; mono?: boolean; strong?: boolean }) { return <div className="flex items-center justify-between gap-4 text-sm"><span className="text-muted-foreground">{label}</span><span className={`${mono ? "font-mono" : ""} ${strong ? "text-lg font-semibold text-foreground" : "text-right font-medium"}`}>{value}</span></div> }
function PaymentState({ state, invoice }: { state: "ready" | "success" | "failed"; invoice: typeof invoices[number] }) { if (state === "success") return <Card className="flex flex-col justify-between border-success/30 bg-success/5 p-6"><div><CheckCircle2 className="size-8 text-success" /><h2 className="mt-4 text-2xl font-semibold">Payment ready to confirm</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">In production, a webhook would now mark the payment as succeeded, confirm the shipment, generate {invoice.number}, and send an AgentMail receipt.</p></div><div className="mt-8 flex flex-col gap-3 rounded-lg border border-success/20 bg-background/60 p-4 text-sm"><Row label="Payment status" value="Succeeded (preview)" strong /><Row label="Invoice" value={invoice.number} mono /><Row label="Receipt" value="Queued (preview)" /></div></Card>; if (state === "failed") return <Card className="flex flex-col justify-between border-destructive/30 bg-destructive/5 p-6"><div><AlertCircle className="size-8 text-destructive" /><h2 className="mt-4 text-2xl font-semibold">Payment failed</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">No shipment was confirmed and no invoice was issued. Retry after connecting a payment provider.</p></div><Button variant="outline" className="mt-8" onClick={() => window.location.reload()}>Try again</Button></Card>; return <Card className="flex flex-col justify-between p-6"><div><CreditCard className="size-8 text-primary" /><h2 className="mt-4 text-2xl font-semibold">Payment is not connected</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">Choose a simulation above to preview the success and failure states without creating a charge.</p></div><div className="mt-8 rounded-lg border border-dashed p-4 text-sm text-muted-foreground">No payment method is stored. Stripe integration is intentionally not enabled.</div></Card> }
function InvoicePanel({ invoice, onPrint, onDownload }: { invoice: typeof invoices[number]; onPrint: () => void; onDownload: () => void }) { return <div className="grid gap-5 lg:grid-cols-[1fr_320px]"><Card className="p-6 md:p-8 print:border-0 print:shadow-none"><div className="flex items-start justify-between gap-4 border-b border-border pb-6"><div><p className="font-mono text-xs uppercase tracking-[0.2em] text-primary">UNIFET LOGISTICS</p><h2 className="mt-3 text-3xl font-bold">Invoice</h2><p className="mt-1 font-mono text-sm text-muted-foreground">{invoice.number}</p></div><div className="text-right text-sm"><p className="font-medium">Issued {invoice.date}</p><Badge variant="outline" className={statusStyles[invoice.status]}>{invoice.status}</Badge></div></div><div className="grid gap-5 py-6 text-sm sm:grid-cols-2"><div><p className="text-xs uppercase tracking-wider text-muted-foreground">Bill to</p><p className="mt-2 font-medium">{invoice.customer}</p><p className="text-muted-foreground">{invoice.email}</p></div><div className="sm:text-right"><p className="text-xs uppercase tracking-wider text-muted-foreground">Shipment</p><p className="mt-2 font-mono">{invoice.shipment}</p><p className="text-muted-foreground">{invoice.service} service</p></div></div><div className="overflow-hidden rounded-lg border"><div className="flex justify-between bg-muted/40 p-4 text-sm font-medium"><span>Shipment service</span><span>Amount</span></div><div className="flex justify-between p-4 text-sm"><span>{invoice.service} shipping · {invoice.shipment}</span><span className="font-mono">${invoice.amount.toFixed(2)}</span></div><div className="flex justify-between border-t p-4 font-semibold"><span>Total</span><span className="font-mono">${invoice.amount.toFixed(2)} USD</span></div></div><p className="mt-6 text-xs leading-5 text-muted-foreground">Preview invoice only. No payment was processed and this document is not a tax receipt.</p></Card><Card className="h-fit p-5"><h3 className="font-semibold">Invoice actions</h3><div className="mt-4 flex flex-col gap-2"><Button onClick={onPrint}><Printer /> Print invoice</Button><Button variant="outline" onClick={onDownload}><ArrowDownToLine /> Download PDF (preview)</Button><Button variant="outline"><Mail /> Preview receipt email</Button></div><div className="mt-5 rounded-lg bg-muted/40 p-3 text-xs leading-5 text-muted-foreground"><FileText className="mb-2 size-4 text-primary" />When payments are connected, this panel will be backed by persisted invoices and webhook-confirmed payment records.</div></Card></div> }
