import Link from "next/link"
import { and, desc, eq, ilike, or } from "drizzle-orm"
import { ArrowLeft, Download, Plus, Search } from "lucide-react"
import { db } from "@/lib/db"
import { shipments } from "@/lib/db/schema"

const statuses = ["pending", "confirmed", "processing", "picked_up", "in_transit", "arrived_at_facility", "out_for_delivery", "delivered", "delayed", "on_hold", "returned", "cancelled"]
const label = (status: string) => status.replaceAll("_", " ").replace(/\b\w/g, (char) => char.toUpperCase())
const tone = (status: string) => status === "delivered" ? "bg-[#123e31] text-[#8be0ba]" : ["delayed", "cancelled", "returned"].includes(status) ? "bg-[#4a1f28] text-[#ff9b9f]" : "bg-[#173653] text-[#9bc8ee]"

export default async function AdminOrdersPage({ searchParams }: { searchParams: Promise<{ q?: string; status?: string }> }) {
  const params = await searchParams
  const q = params.q?.trim() ?? ""
  const selectedStatus = params.status ?? ""
  const filters = [q ? or(ilike(shipments.trackingNumber, `%${q}%`), ilike(shipments.origin, `%${q}%`), ilike(shipments.destination, `%${q}%`), ilike(shipments.driverName, `%${q}%`)) : undefined, selectedStatus ? eq(shipments.status, selectedStatus) : undefined].filter(Boolean)
  const orders = await db.select().from(shipments).where(filters.length ? and(...filters) : undefined).orderBy(desc(shipments.updatedAt))
  return <section className="flex flex-col gap-6">
    <div className="flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><Link href="/admin/dashboard" className="inline-flex items-center gap-2 text-sm text-[#9fb4c3] hover:text-white"><ArrowLeft className="size-4" /> Dashboard</Link><p className="mt-5 font-mono text-xs uppercase tracking-[0.22em] text-[#df3038]">Operations / shipment control</p><h1 className="mt-2 text-4xl font-semibold tracking-tight">Shipments</h1><p className="mt-2 text-[#9fb4c3]">Search, filter, and manage every parcel in the network.</p></div><div className="flex gap-3"><button className="inline-flex items-center gap-2 rounded-xl border border-[#1d3548] px-4 py-3 text-sm font-semibold text-[#c5d3db] hover:bg-[#112b40]"><Download className="size-4" /> Export CSV</button><button className="inline-flex items-center gap-2 rounded-xl bg-[#df3038] px-4 py-3 text-sm font-semibold text-white hover:bg-[#bd252d]"><Plus className="size-4" /> Create shipment</button></div></div>
    <form className="grid gap-3 rounded-2xl border border-[#1d3548] bg-[#0a1a2b] p-4 md:grid-cols-[1fr_220px_auto]" method="get"><label className="relative block"><Search className="absolute left-3 top-3 size-4 text-[#6f8797]" /><input name="q" defaultValue={q} placeholder="Tracking, origin, destination, driver" className="w-full rounded-xl border border-[#1d3548] bg-[#071321] py-2.5 pl-10 pr-3 text-sm text-white outline-none ring-[#df3038] placeholder:text-[#6f8797] focus:ring-2" /></label><select name="status" defaultValue={selectedStatus} className="rounded-xl border border-[#1d3548] bg-[#071321] px-3 py-2.5 text-sm text-[#c5d3db] outline-none focus:ring-2 focus:ring-[#df3038]"><option value="">All statuses</option>{statuses.map((status) => <option key={status} value={status}>{label(status)}</option>)}</select><button className="rounded-xl border border-[#1d3548] px-5 py-2.5 text-sm font-semibold hover:bg-[#112b40]">Apply filters</button></form>
    <div className="overflow-hidden rounded-2xl border border-[#1d3548] bg-[#0a1a2b]"><div className="flex items-center justify-between border-b border-[#1d3548] px-5 py-4"><p className="text-sm text-[#9fb4c3]"><span className="font-semibold text-white">{orders.length}</span> shipments shown</p><p className="text-xs text-[#6f8797]">Sorted by latest update</p></div><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="border-b border-[#1d3548] text-xs uppercase tracking-wider text-[#6f8797]"><tr><th className="px-5 py-4">Tracking</th><th className="px-5 py-4">Route</th><th className="px-5 py-4">Status</th><th className="px-5 py-4">Driver</th><th className="px-5 py-4">ETA</th><th className="px-5 py-4">Updated</th></tr></thead><tbody>{orders.map((order) => <tr key={order.id} className="border-b border-[#1d3548] last:border-0 hover:bg-[#0d2235]"><td className="px-5 py-4 font-mono font-semibold text-[#ff8b8f]">{order.trackingNumber}</td><td className="px-5 py-4 text-[#c5d3db]">{order.origin} <span className="text-[#6f8797]">→</span> {order.destination}</td><td className="px-5 py-4"><span className={`rounded-full px-3 py-1 text-xs font-semibold ${tone(order.status)}`}>{label(order.status)}</span></td><td className="px-5 py-4 text-[#9fb4c3]">{order.driverName ?? "Unassigned"}</td><td className="px-5 py-4 text-[#9fb4c3]">{order.eta ? new Date(order.eta).toLocaleDateString() : "—"}</td><td className="px-5 py-4 text-[#9fb4c3]">{new Date(order.updatedAt).toLocaleDateString()}</td></tr>)}</tbody></table></div>{!orders.length ? <div className="p-14 text-center"><p className="font-semibold">No shipments match these filters.</p><p className="mt-2 text-sm text-[#9fb4c3]">Try another tracking number, route, or status.</p></div> : null}</div>
  </section>
}
