import Link from "next/link";
import { createClient } from "@/lib/supabase/server";

export default async function AdminDashboardPage() {
  const supabase = await createClient();
  const [{ count: shipments }, { count: customers }, { data: recent }] = await Promise.all([
    supabase.from("shipments").select("id", { count: "exact", head: true }),
    supabase.from("profiles").select("id", { count: "exact", head: true }),
    supabase.from("shipments").select("id, tracking_number, status, origin, destination, updated_at").order("updated_at", { ascending: false }).limit(6),
  ]);
  const active = (recent ?? []).filter((item) => !["delivered", "cancelled"].includes(String(item.status).toLowerCase())).length;
  return <section className="flex flex-col gap-8"><div><p className="font-mono text-xs uppercase tracking-[0.2em] text-[#8a1018]">Tuesday, operations brief</p><h1 className="mt-2 font-serif text-4xl font-bold tracking-tight">Good morning, captain.</h1><p className="mt-2 text-[#6d5e5a]">One view for every parcel, customer, and delivery exception.</p></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Total shipments", shipments ?? 0], ["Active routes", active], ["Customers", customers ?? 0], ["On-time target", "98.4%"]].map(([label, value]) => <div key={String(label)} className="rounded-2xl border border-[#d9c9a2] bg-[#fffdf7] p-5"><p className="text-sm text-[#6d5e5a]">{label}</p><p className="mt-3 font-serif text-3xl font-bold text-[#67040b]">{value}</p></div>)}</div><div className="grid gap-6 xl:grid-cols-[1.4fr_0.6fr]"><div className="rounded-2xl border border-[#d9c9a2] bg-[#fffdf7] p-5"><div className="flex items-center justify-between"><div><h2 className="font-serif text-2xl font-bold">Latest shipments</h2><p className="text-sm text-[#6d5e5a]">Most recently updated in Supabase.</p></div><Link href="/admin/orders" className="text-sm font-semibold text-[#8a1018]">View all</Link></div><div className="mt-5 flex flex-col gap-3">{(recent ?? []).map((item) => <div key={item.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-[#eadfc5] p-4"><div><p className="font-mono text-sm font-bold">{item.tracking_number}</p><p className="text-sm text-[#6d5e5a]">{item.origin} → {item.destination}</p></div><span className="rounded-full bg-[#f1ead9] px-3 py-1 text-xs font-semibold capitalize text-[#67040b]">{String(item.status).replaceAll("_", " ")}</span></div>)}{!recent?.length ? <p className="py-8 text-center text-sm text-[#6d5e5a]">No shipments have been created yet.</p> : null}</div></div><div className="rounded-2xl bg-[#67040b] p-6 text-[#fff7df]"><p className="font-mono text-xs uppercase tracking-widest text-[#dcb45a]">Quick action</p><h2 className="mt-3 font-serif text-3xl font-bold">Keep the fleet moving.</h2><p className="mt-3 text-sm leading-6 text-[#f4dfb0]">Create, update, and monitor shipments from the orders workspace.</p><Link href="/admin/orders" className="mt-6 inline-flex rounded-lg bg-[#dcb45a] px-4 py-3 font-semibold text-[#250e17]">Manage orders</Link></div></div></section>;
}
